# -*- coding: utf-8 -*-
"""task_1.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

st = input("Enter your string here : ")
i = input("Enter your integer here : ")

print(st)
print(i)