# -*- coding: utf-8 -*-
"""task_1.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

n1 = int(input("Enter your string here : "))
n2 = int(input("Enter your integer here : "))

sum = n1 + n2
mul = n1 * n2
print("Summation: ",sum)
print("Multiplication: ",mul)