# -*- coding: utf-8 -*-
"""Task 01(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sRGxM9itgH14jeb4-cdcBGOE9mud9LuQ
"""

input=open("/content/input1(a).txt","r")
output=open("/content/output1(b).txt","w")

x=input.readline().split()
l=int(x[0])
target=int(x[1])
#print(l,target)
arr=input.readline().split()
lst=[int(i) for i in arr]
#print(lst)

flag = False
for i in range(l-1):

    for j in range(i+1,l):

        if lst[i]+lst[j] == target:

            output.write(f"{i+1} {j+1}")

            flag = True

    if flag:
        break

if not flag:
    output.write(f"IMPOSSIBLE")

input.close()
output.close()