# -*- coding: utf-8 -*-
"""Class Task _1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

num = int(input())

if num % 2 == 0:
    print("The number is Even")
else:
    print("The number is odd")