# -*- coding: utf-8 -*-
"""Class Task _4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

num = int(input())

if num % 2 == 0 and num % 5 == 0:
    print(num)
else:
    print("Not multiple of 2 and 5 both")