# -*- coding: utf-8 -*-
"""Class Task _2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

num1 = int(input())
num2 = int(input())

if num1 > num2:
    print("First is greater")

elif num1 == num2:
    print("The numbers are equal")

else:
    print("Second is greater")