# -*- coding: utf-8 -*-
"""task1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

input1_b = open('/content/input1(b).txt', 'r')
output1_b = open('/content/output1(b).txt','w')

nodes, edges = map(int, input1_b.readline().strip().split())
adj_matrix = [[] for i in range(nodes+1)]

for edge_info in range(edges):
    u, v, w = map(int, input1_b.readline().strip().split())
    adj_matrix[u].append((v, w))

for i in range(nodes+1):
    output1_b.write(f"{i} : ")
    for pair in adj_matrix[i]:
        output1_b.write(f"{pair} ")
    output1_b.write(f"\n")

input1_b.close()
output1_b.close()