# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

def bfs(u):
    visited[u] = 1
    travarsal.append(u)

    queue = []
    queue.append(u)

    while len(queue) != 0:
        frnt = queue[0]
        queue.pop(0)

        for v in adj_list[frnt]:
            if visited[v]:
                continue
            queue.append(v)
            visited[v] = 1
            travarsal.append(v)



input2 = open('/content/input2.txt', 'r')
output2 = open('/content/output2.txt','w')

node, edge = map(int, input2.readline().split())

adj_list = [[] for i in range(node+1)]
visited = [0] * (node+1)

for i in range(edge):
  u, v = map(int, input2.readline().split())
  adj_list[u].append(v)
  adj_list[v].append(u)


travarsal = []
bfs(1)

for v in travarsal:
  output2.write(f"{v} ")


input2.close()
output2.close()