# -*- coding: utf-8 -*-
"""task1(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

input1_a = open('/content/input1(a).txt', 'r')
output1_a = open('/content/output1(a).txt','w')

nodes, edges = map(int, input1_a.readline().strip().split())
adj_matrix = [[0 for i in range(nodes+1)] for i in range(nodes+1)]

for edge_info in range(edges):
    u, v, w = map(int, input1_a.readline().strip().split())
    adj_matrix[u][v] = w

for i in range(nodes+1):
    for j in range(nodes+1):
        output1_a.write(f"{adj_matrix[i][j]} ")
    output1_a.write(f"\n")


input1_a.close()
output1_a.close()