# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

def dfs(u):
    visited[u] = 1
    travarsal.append(u)

    for v in adj_list[u]:
        if visited[v]:
            continue
        dfs(v)




input3 = open('/content/input3.txt', 'r')
output3 = open('/content/output3.txt','w')

node, edge = map(int, input3.readline().split())

adj_list = [[] for i in range(node+1)]
visited = [0] * (node+1)

for i in range(edge):
  u, v = map(int, input3.readline().split())
  adj_list[u].append(v)
  adj_list[v].append(u)


travarsal = []
dfs(1)

for v in travarsal:
  output3.write(f"{v} ")


input3.close()
output3.close()