# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

def check_cycle(u):
    dfs_visited[u] = 1
    visited[u] = 1


    for v in adj_list[u]:

        if dfs_visited[v] == 0:
            check_cycle(v)

        if visited[v]:
            return True

    visited[u] = 0
    return False


input4 = open('/content/input4.txt', 'r')
output4 = open('/content/output4.txt','w')

node, edge = map(int, input4.readline().split())

adj_list = [[] for i in range(node+1)]
visited = [0] * (node+1)
dfs_visited = [0] * (node+1)

for i in range(edge):
  u, v = map(int, input4.readline().split())
  adj_list[u].append(v)


flag = check_cycle(1)

if flag:
  output4.write(f"YES")
else:
  output4.write("NO")


input4.close()
output4.close()