# -*- coding: utf-8 -*-
"""Class Task_3.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

import math

def circle(radius):
    """
    Calculate the area of a circle given its radius.
    """
    return math.pi * radius**2

def sphere(radius):
    """
    Calculate the volume of a sphere given its radius.
    """
    return (4/3) * math.pi * radius**3

def fitting(diameter1, diameter2, dimension):
    """
    Calculate the area/volume of circles/spheres and determine fitting relationships.
    """
    # Calculate radius for circles
    radius1 = diameter1 / 2
    radius2 = diameter2 / 2

    # Calculate area/volume based on dimension
    if dimension == 3:
        volume1 = sphere(radius1)
        volume2 = sphere(radius2)
        fitting_relation = "fit inside" if volume1 < volume2 else "cannot fit inside"
    elif dimension == 2:
        area1 = circle(radius1)
        area2 = circle(radius2)
        fitting_relation = "fit inside" if area1 < area2 else "cannot fit inside"
    else:
        raise ValueError("Invalid dimension. Only 2 or 3 dimensions are supported.")

    # Calculate remaining space
    remaining_space = abs(volume2 - volume1) if dimension == 3 else abs(area2 - area1)

    # Print results
    print(f"Area/Volume of first circle/sphere: {area1 if dimension == 2 else volume1}")
    print(f"Area/Volume of second circle/sphere: {area2 if dimension == 2 else volume2}")
    print(f"The smaller circle/sphere can {fitting_relation} the larger one.")
    print(f"Remaining space: {remaining_space}")

# Example usage
fitting(10, 8, 2)  # Example with circles
fitting(10, 8, 3)  # Example with spheres