# -*- coding: utf-8 -*-
"""Class Task_1.4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def is_pos(n):
    return n > 0

def is_even(n):

    if n % 2 == 0:
        return True
    else:
        return False

def sequence(num):

    if is_pos(num):

        for i in range(0,num+1,2):
            print(i,end=' ')
    else:
        if is_even(num):
            for j in range(num+1,0,2):
                print(j,end=' ')
        else:
            for k in range(num,0,2):
                print(k,end=' ')

sequence(10)
print()
sequence(-7)
print()
sequence(7)
print()
sequence(-8)