# -*- coding: utf-8 -*-
"""Class Task_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def even_checker(num):

    if num % 2 == 0:
        print("Even!!")
    else:
        print("Odd!!")
even_checker(10)
even_checker(17)