# -*- coding: utf-8 -*-
"""Class Task_5.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def reverse_printing(start,n):

    for i in range(n,start-1,-1):
                   print(i,end="  ")
reverse_printing(1,6)