# -*- coding: utf-8 -*-
"""Class Task_1.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def is_even(num):

    if num % 2 == 0:
        return True
    else:
        return False
result = is_even(10)
print( result )
result = is_even(17)
print( result )