# -*- coding: utf-8 -*-
"""Class Task_5.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def one_to_N(start,n):

    for i in range(start,n+1):
        print(i,end=' ')
one_to_N(1,5)