# -*- coding: utf-8 -*-
"""Home Task_3.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def calc_tax(age,salary):

    if age < 18 or salary < 10000:
        return 0
    else:
        if 10000 <= salary <= 20000:
            tax = (salary * 7) / 100
            return tax
        elif 20000 < salary:
            tax = (salary * 14) / 100
            return tax



t = calc_tax(16,20000)
print(t)
t = calc_tax(20,100000)
print(t)