# -*- coding: utf-8 -*-
"""Home Task_1.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def is_perfect(num):
    sum = 0

    for i in range(1,num):
        if num % i == 0:
            sum += i
    if sum == num:
        return True
    else:
        return False

def is_prime(num):
    if num < 2:
        return False
    for i  in range(2,num):
        if num % i == 0:
            return False
    return True

def special_sum(n):

    sum = 0

    for i in range(1,n+1):
        if is_prime(i) or is_perfect(i):
            #print(i,end=" ")
            sum += i
    return sum

result = special_sum(30)
print(result)