# -*- coding: utf-8 -*-
"""Home Task_4.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def reverse_digits(n):

    if n < 10:
        print(n)
    else:
        print(n % 10)
        reverse_digits(n // 10)

number = int(input("Enter an integer: "))
reverse_digits(number)