# -*- coding: utf-8 -*-
"""Home Task_1.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def is_perfect(num):
    sum = 0

    for i in range(1,num):
        if num % i == 0:
            sum += i
    if sum == num:
        return True
    else:
        return False



result = is_perfect(30)
print(result)