# -*- coding: utf-8 -*-
"""Home Task _3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

c = int(input())

remain = c % 3
each = c // 3

print(f"Each friend will receive {each} chocolates")
print(f"The number of remaining chocolates is {remain}")