# -*- coding: utf-8 -*-
"""task_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

weight = int(input("Enter your total weight of the shipment here : "))


x = weight // 4
x = x*4

print(x)