# -*- coding: utf-8 -*-
"""task_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

m = int(input("Enter your string here : "))
n = int(input("Enter your integer here : "))

result = m**n

print(m,"^",n,":",result)
# Using format
print(f"{m}^{n}: {result}")