# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

from queue import PriorityQueue


def top_sort_bfs():
    pq = PriorityQueue ()

    for i in range(1, node+1):
        if in_cnt[i] == 0:
            pq.put(i)
    count = 0
    while not pq.empty():
        frnt = pq.get()
        order.append(frnt)
        count += 1

        for v in adj_list[frnt]:
            in_cnt[v] -= 1
            if in_cnt[v] == 0:
                pq.put(v)
    return count


input2 = open("/content/input2.txt", 'r')
output2 = open("/content/output2.txt", 'w')

node, edge = map(int, input2.readline().split())

adj_list = [[] for i in range(node+1)]
in_cnt = [0] * (node+1)

for i in range(edge):
  u, v = map(int, input2.readline().split())
  adj_list[u].append(v)
  in_cnt[v] += 1

order = []
count = top_sort_bfs()

if count == node:
    for v in order:
        output2.write(f"{v} ")

else:
    output2.write(f"Impossible")

input2.close()
output2.close()