# -*- coding: utf-8 -*-
"""Class Task _1(b)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

flag = 18
while flag <= 63:

    if flag == 63:
        print(flag,end="")
    else:
        print(flag, end=', ')

    flag = flag + 9