# -*- coding: utf-8 -*-
"""Home Task _7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

test = 1
j = 0
k = 100
while (k > 0):
  while ( j < k ):
    test += k + j -21
    print(1 + int (test / 2))
    j += 10
  k -= 10
  test = 1
'''
41
85
135
189
249
313
383
457
537
621
'''