# -*- coding: utf-8 -*-
"""Home Task _1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

num = int(input())

sum  = 0
i = 7

while i < num:

    if (i % 7 == 0 or i % 9 ==0) and not (i % 7 == 0 and i % 9 ==0):
            sum += i

    i += 1

print(sum)