# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

#Task-2

def bubbleSort(arr):
    is_sorted = True
    for i in range(len(arr)-1):
        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1]:
                is_sorted = False
                arr[j], arr[j+1] = arr[j+1], arr[j]

        if is_sorted:
            break

input_2=open("/content/input3.txt","r")
output_2=open("/content/output3.txt","w")

n = int(input_2.readline().strip())
lst = input_2.readline().strip().split()
lst = [int(i) for i in lst]

bubbleSort(lst)
#print(lst)

for i in lst:
    output_2.write(f"{i} ")