# -*- coding: utf-8 -*-
"""Home Task _1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

st = input()
result = ''
for i in range(len(st)-1):
    if st[i] == st[i+1]:
        continue
    else:
        result += st[i]
print(result)