# -*- coding: utf-8 -*-
"""Home Task _2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

st = input()
st1, st2 = st.split(", ")
result = ''
i = 0
j = 0
c = 0

while i < len(st1) and j < len(st2):

    if c % 2 == 0:
        result += st1[i]
        i += 1
    else:
        result += st2[j]
        j += 1
    c += 1

result += st1[i:]
result += st2[j:]

print(result)

# Another way
'''
def mix_strings(str1, str2):
    mixed_string = ""
    min_length = min(len(str1), len(str2))

    for i in range(min_length):
        mixed_string += str1[i] + str2[i]

    mixed_string += str1[min_length:] + str2[min_length:]

    return mixed_string


user_input = input("Enter two strings separated by a comma and a space: ")
input_strings = user_input.split(", ")
result = mix_strings(input_strings[0], input_strings[1])
print("Mixed String:", result)
'''