# -*- coding: utf-8 -*-
"""task_18

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that will check whether the number is armstrong number or not.

num = input("Enter your number :")


l = len(num)
num = int(num)
check = num
sum = 0
for i in range(l):

    temp = num % 10
    num = num // 10
    sum += temp**l

if check  == sum:
    print("The given number is an Armstrong number")

else:
    print("The given number is an Armstrong number")