# -*- coding: utf-8 -*-
"""task_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7WEiJQsG21IbHHiJ1mT25SMNmnyv23A
"""

# Write a program that will convert celsius value to fahrenheit

C = float(input("Enter the temperature in Celsius : "))

F = C * (9/5) + 32.

print("Temperature in Fahrenheit : ", F)