# -*- coding: utf-8 -*-
"""task_50

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program which can remove a particular character from a string.

st = input("Enter your string : ")
ch = int(input("Enter the index of a particular character : "))

x = st[:ch-1]
y = st[ch:]
print("The left over string is : ",x+y)