# -*- coding: utf-8 -*-
"""task_58

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

'''
Write a program that can reverse words of a given string.
Eg if the input is Hello how are you
Output should be you are how Hello
'''
st = input("Enter your string here : ")

x = st.split()

y = []

for i in range(len(x)-1,-1,-1):

    y.append(x[i])

y = ' '.join(y)

print("The reversed string of the given string is : ",y)