# -*- coding: utf-8 -*-
"""task_74

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to merge two given dictionary

dct_1 = {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

dct_2 = {'a':500,'b':100}

dct = {}

for i in dct_1:

    dct[i] = dct_1[i]

for i in dct_2:

    dct[i] = dct_2[i]

print("Merged dictionary is : ",dct)

