# -*- coding: utf-8 -*-
"""task_66

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that can perform union and intersection on 2 given list.

l_1 = [1,2,3,4,4,5,6,7,9]
l_2 = [3,5,9,23,56,3,7,8,9]

u = []
inter = []

#Union
for i in l_1:
    if i not in u:
        u.append(i)

for j in l_2:
    if j not in u:
        u.append(j)

for i in l_1:
    if i in l_2:
        inter.append(i)

print(u)
print(inter)

