# -*- coding: utf-8 -*-
"""task_39

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

'''
Write a program to print the following pattern
1
1 2 1
1 2 3 2 1
1 2 3 4 3 2 1
1 2 3 4 5 4 3 2 1

'''
r = int(input("Enter your row number : ")
)
for i in range(1,r+1):

    for j in range(1,i+1):

        print(j, end = " ")
    #print()

    for k in range(i-1,0,-1):
        print(k,end = " ")

    print()