# -*- coding: utf-8 -*-
"""task_63

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to merge 2 list without using the + operator

x = [2, 4, 6, 8, 10]
y = [1, 3, 5, 7, 9]

lst = []

for i in range(len(x)):

    lst.append(x[i])
for i in range(len(y)):

    lst.append(y[i])


print("Merged list : ",lst)

