# -*- coding: utf-8 -*-
"""task_28

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Print all the armstrong numbers in the range of 100 to 1000


for i in range(100,10001):

    l = len(str(100))
    #print(l)
    num = i
    sum = 0
    for j in range(l):
        temp = num % 10
        sum += temp**l
        num = num//10
    if sum == i:
        print(i, end=" ")
    #sum = 0