# -*- coding: utf-8 -*-
"""task_54

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a python program to find the max item from a list without using the max function


lst = [10,3,6,68,90,200,5,6,8,9,46,754,6788,124,67,76]

max_value = lst[0]

for i in lst:

    if i > max_value:

        max_value = i

print("The max item from the list is : ",max_value)