# -*- coding: utf-8 -*-
"""task_47

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Count the frequency of a particular character in a provided string. Eg 'hello how are you' is the string, the frequency of h in this string is 2.

st = input("Enter your preferred string here : ")

ch = input("Enter the character you wanted to count : ")

c = 0

for i in st:

    if i in ch:
        c += 1

print(f"Total number of '{ch}' is {c}")