# -*- coding: utf-8 -*-
"""task_37

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

'''
Write a program to print the following pattern
*
**
***
**
*

'''
for i in range(1,6):
    if i <= 3:
        for j in range(i):
            print('*', end='')
    else:
        for j in range(6 - i, 0, -1):
            print('*', end='')

    print()

    '''
for i in range(1, 5):
    if i <= 3:
        print('*' * i)
    else:
        for j in range(3, 0, -1):
            print('*' * j)

    '''