# -*- coding: utf-8 -*-
"""task_33

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Take a number from the user and find the number of digits in it.

a = int(input("Enter your number here : "))

flag = 0

while (a > 0):

    a = a // 10

    flag += 1

print("Total number of digits : ", flag)

