# -*- coding: utf-8 -*-
"""task_52

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a python program to remove all the duplicates from a list

lst = [1,2,2,2,3,3,3,5,6,7,8,9,9,8,7,67,9,0,9,0,9,8,7,4]

e_lst = []

for i in range(len(lst)):

    if lst[i] not in e_lst:
        e_lst.append(lst[i])

print(e_lst)