# -*- coding: utf-8 -*-
"""task_49

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Count the number of vowels in a string provided by the user.

st = input("Enter your string here : ")

vowl = ["a", "e", "i", "o", "u"]

c  = 0
for i in st:

    if i in vowl:

        c += 1

print("Total number of vowels are : ", c)