# -*- coding: utf-8 -*-
"""task_29

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

''''
The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year.
You have to write a program to find out the population at the end of each of the last 10 years.
For eg current population is 10000 so the output should be like this:
10th year - 10000
9th year - 9000
8th year - 8100 and so on

'''

flag = 10

x = 10000
print(flag,"th year - ",int(x))

while True:

    y = x - ((x * 10)/100)
    x = y
    flag -= 1

    print(flag,"th year - ",int(x))

    if flag == 1:
        break