# -*- coding: utf-8 -*-
"""task_06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GoKwkiQV9xBtVhhxX5Hh9j2-SlBHCJzS
"""

# Write a program that will tell whether the number entered by the user is odd or even.

x = int(input('Enter a number : '))

if x % 2 == 0:
    print("The number is Even")
else:
    print("The number is Odd")