# -*- coding: utf-8 -*-
"""task_21

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a menu driven program - 1.cm to inches  2.km to miles  3.usd to taka  4.exit

x = int(input('''
Hi there! what would like to do
    1.Enter 1 if you want to convert cm to inches,
    2.Enter 2 if you want to convert kl to miles,
    3.Enter 3 if you want to usd to taka
    4.Exit
'''))

if x == 1:
    cm = float(input("Enter your value in cm : "))
    inch = cm * 0.394
    print("Your value in inches : ",inch)
elif x == 2:
    km = float(input("Enter your value in km : "))
    mile = km * 0.609
    print("Your value in miles : ",mile)
elif x == 3:
    usd = float(input("Enter your value in usd : "))
    taka = usd * 109.79
    print("Your value in miles : ",taka)
else:
    print("Exit")