# -*- coding: utf-8 -*-
"""task_10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit

cost_price, selling_price = map(float, input("Enter the cost and selling price here : ").split())

if selling_price > cost_price:
    profit = selling_price - cost_price
    print("It's a profit and it's about : ",profit)
elif selling_price == cost_price:
    print("No loss")
else:
    loss = cost_price - selling_price
    print("It's a loss and it's about : ",loss)