# -*- coding: utf-8 -*-
"""task_44

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

#  Write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers.

sum = 0
c = 0

while True:

    n = int(input("Enter your numbers here : "))

    if n == 0:
        break

    else:
        sum += n
        c += 1

avg = sum / c

print("Total sum of your given numbers are : ", sum)
print("Average of your given numbers are : ", avg)