# -*- coding: utf-8 -*-
"""task_35

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Find the reverse of a number provided by the user(any number of digit)

n = int(input("Enter your number : "))
l = len(str(n))
rev = 0

'''
Using while loop

while n > 0:
    temp  = n % 10
    n = n // 10

    rev = (rev * 10) + temp

print("Revered value of the given number is : ", rev)

'''

for i in range(0, l):

    temp  = n % 10
    n = n // 10

    rev = (rev * 10) + temp

print("Revered value of the given number is : ", rev)

