# -*- coding: utf-8 -*-
"""task_11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to find the simple interest when the value of principle,rate of interest and time period is given.

p = int(input("Enter your principle : "))
r = int(input("Enter your rate of interest : "))
t = int(input("Enter your time period : "))

simple_interest = (p*r*t)/100

print("Your simple interest is : ",simple_interest)

n = p + simple_interest

print("Final amount is : ",n)