# -*- coding: utf-8 -*-
"""task_61

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to check if a list is in ascending order or not

lst = [1,2,4,5,6,7,8,9,10]

flag = True

for i in range(len(lst)-1):

    if lst[i] > lst[i+1]:
        flag = False
        break

if flag:
    print("Ascending ordered")
else:
    print("Not in ascending ordered")