# -*- coding: utf-8 -*-
"""task_76

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that converts integer to string without using str()

def converter(num):

    digits = '0123456789'

    output = ''


    while num != 0:

        temp = num % 10
        output += digits[temp]
        num = num // 10
    return output

print(type(converter(100)))

