# -*- coding: utf-8 -*-
"""task_46

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Find the length of a given string without using the len() function.

st = "ShahidulHaqueShaheen"

c = 0

for i in st:
    c +=1

print("Length of the string is : ",c)