# -*- coding: utf-8 -*-
"""task_07

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that will tell whether the given year is a leap year or not.

year = int(input("Enter your year here : "))

if year % 4 == 0:
    print("Leap year")

else:
    print("Not a leap year")