# -*- coding: utf-8 -*-
"""task_75

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

'''
Write a program to swap the key value pair for max and min values
Eg if the dict is like this {‘a’:1,’b’:2,’c’:3}
Output should be {a:3,b:2,c:1}

'''


dct = {'a':100,'b':200,'c':300,'d':400}

max_val = max(dct.values())
min_val = min(dct.values())


for i in dct:

    if dct[i] == max_val:

        print(dct[i])
        break

for j in dct:

    if dct[j] == min_val:

        print(dct[j])
        break

dct[i] = min_val
dct[j] = max_val


print(dct)

