# -*- coding: utf-8 -*-
"""task_08

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to find the euclidean distance between two coordinates.

x1, x2, y1, y2 = map(float, input("Enter your two coordinates here : ").split())

dist = ((x2-x1)**2 + (y2-y1)**2)**0.5

print("The euclidean distance between two coordinates is : ",dist)