# -*- coding: utf-8 -*-
"""task_25

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that can find the factorial of a given number provided by the user.

n = int(input("Enter your number here : "))

if n > 0:
    fac = 1
    for i in range(1,n+1):
        fac = fac*i
        #print(fac)
    print("The factorial of ",n," is : ",fac)
else:
    print("Factorial is not defined for negative numbers.")