# -*- coding: utf-8 -*-
"""task_64

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to replace an item with a different item if found in the list

lst = [2, 4, 6, 8, 10, 1, 3, 5, 7, 9]

find = int(input("Enter your number : "))

replace = int(input("Enter your number that you want to replace : "))

for i in range(len(lst)):

    if find == lst[i]:
        lst[i] = replace
        print(lst)
        break


else:
    print("Not found")

