# -*- coding: utf-8 -*-
"""task_23

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to find the sum of first n numbers, where n will be provided by the user. Eg if the user provides n=10 the output should be 55.

n = int(input("Enter your number here : "))

# sum = 0
# for i in range(1,n+1):
#     sum += i

# Using formula
sum = (n*(n+1))//2

print("Total till n : ",sum)