# -*- coding: utf-8 -*-
"""task_45

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Extract username from a given email.
#Eg if the email is nitish24singh@gmail.com then the username should be nitish24singh

st = "mdshahidulhaque098@gmail.com"

for i in st:

    if i != '@':
        print(i, end = "")
    else:
        break

'''
st = "mdshahidulhaque098@gmail.com"

user_name, mail = st.split("@")

print(user_name)
'''