# -*- coding: utf-8 -*-
"""task_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

List_one = [1, 3, 5, 7, 9, 10]
List_two = [2, 4, 6, 8]

if List_one:
    List_one[-1:] = List_two
    print(List_one)
else:
    print(List_two)