# -*- coding: utf-8 -*-
"""Task_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def with_append():

    lst = []

    for i in range(5):
        temp = int(input("Enter your number here : "))
        lst.append(temp)

        print(f"List after this {temp} value : {lst}")

def without_append():

    lst = []

    for i in range(5):
        temp = int(input("Enter your number here : "))
        lst += [temp]

        print(f"List after this {temp} value : {lst}")


with_append()
without_append()