# -*- coding: utf-8 -*-
"""task_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

List_one = [1, 4, 3, 2, 5]
List_two = [8, 7, 6, 9]


flag = False
for i in range(len(List_one)):
    if List_one[i] in List_two:
        flag = True
        break
if flag:
    print("True")
else:
    print("False")