# -*- coding: utf-8 -*-
"""task_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def even(lst1,lst2):

    lst = []

    for i in lst1:
        if i % 2 == 0:
            lst.append(i)
    for j in lst2:
        if j % 2 == 0:
            lst.append(j)

    return lst

List_one = [1, 4, 7, 5, 8, 11]
List_two = [6, 1, 3, 9, 12, 15]
result_list = even(List_one, List_two)

print(result_list)