# -*- coding: utf-8 -*-
"""Task-1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

#Task-1(b)

input_2=open("/content/input2.txt","r")
output_2=open("/content/output2.txt","w")


l=int(input_2.readline())
lst=input_2.readlines()
#print(lst)

for i in lst:
    i=i.strip("\n").split()
    x=int(i[1])
    y=i[2]
    z=int(i[3])
    #print(x,y,z)
    if y=="+":
        output_2.write(f"The result of {x} + {z} is {x+z} \n")
    if y=="-":
        output_2.write(f"The result of {x} - {z} is {x-z} \n")
    if y=="/":
        output_2.write(f"The result of {x} / {z} is {x//z} \n")
    if y=="*":
        output_2.write(f"The result of {x} * {z} is {x*z} \n")

output_2.close()
input_2.close()
#print(type(l))