# -*- coding: utf-8 -*-
"""Task-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

#Task-3



def find_time(idx):
  time_li = sp_li[idx][-1].split(":")
  time = int(time_li[0]) + (int(time_li[1]))/100
  return time

input_4 = open('/content/input5.txt', 'r')
output_4 = open('/content/output5.txt','w')

data = input_4.readlines()


sp_li=[]
n=int(data[0])
for e in range(1, n+1):
  sp_li.append(data[e].split(" "))


for i in range(n-1, -1, -1):   # Selection sort
  for j in range(0, i+1):
    if(j==0):
      big_idx = j
      big = sp_li[j]
    if(sp_li[j][0] > big[0]):
      big=sp_li[j]
      big_idx=j
    elif(sp_li[j][0] == big[0]):
      if(find_time(j) <= find_time(big_idx)):
        big=sp_li[j]
        big_idx=j


  sp_li[j], sp_li[big_idx] = sp_li[big_idx], sp_li[j]


for li in sp_li:
  c=0
  for e in li:
    if(c!=6):
      output_4.write(f"{e} ")
    else:
      output_4.write(f"{e} ")
    c+=1




input_4.close()
output_4.close()