# -*- coding: utf-8 -*-
"""Task-1(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15HAIdkL4KT9rGVR_IKpK3eWYrI8qLdz3
"""

#Task-1(a)

input=open("/content/input1.txt","r")
output=open("/content/output1.txt","w")

l=int(input.readline())

for i in range(l):
    num=int(input.readline())
    if num%2==0:
        output.write(f"{num} is an Even number.\n")

    else:
        output.write(f"{num} is an Odd number.\n")

    #print(num)
#--------------------------------------
# input.read()
# input.readline()
# input.readline()
# input.read()
# input.readlines()
#--------------------------------------
# output=open("/content/output1.txt","w")
# output.write("Hello")


# output.close()
#---------------------------------------

#print(type(l))
output.close()
input.close()