# -*- coding: utf-8 -*-
"""task_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def two_elements(lst):

    if len(lst) < 4:
        print("Not possible")
    else:
        temp = lst[2:-2]
        print(temp)


user_input = input("Enter your list here : ").split(',')
user_input = [int(i) for i in user_input]
two_elements(user_input)