# -*- coding: utf-8 -*-
"""task_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def reverse(l):

    lst = []
    for i in range(len(l)-1,-1,-1):
        lst.append(l[i])
    return lst

l = [5, -5, 100, 1, 0]
r = reverse(l)
print(r)