# -*- coding: utf-8 -*-
"""task_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def nested_to_linear(lst):

    result = []

    for i in lst:

        if isinstance(i , list):
            result.extend(nested_to_linear(i))
        else:
            result.append(i)
    return result


nested_list = ["start", 10, [4, 2, [11, [9, "mid", 3, [1, 0], 6]], 8], "Done"]
linear_list = nested_to_linear(nested_list)

print(linear_list)