# -*- coding: utf-8 -*-
"""Class Task _5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

row = int(input("Enter your row here : "))
column = int(input("Enter your column here : "))


for i in range(row):

    for j in range(1,column+1):

        print(j,end='')

    print()