# -*- coding: utf-8 -*-
"""Class Task _3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

num = int(input("Enter your number her : "))


while num != 0:

    temp = num % 10
    if num < 10:
        print(temp, end="")
    else:
        print(temp,end=', ')

    num = num // 10