# -*- coding: utf-8 -*-
"""Class Task _1(a)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

flag = 24
while flag >= -6:

    if flag == -6:
        print(flag,end="")
    else:
        print(flag, end=', ')

    flag = flag - 6