# -*- coding: utf-8 -*-
"""Class Task _4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

num = int(input("Enter your number here : "))

c = 1
i = 1
while i != num:

    if num % i == 0:
        print(i)
        c += 1
    i += 1
print(num)
print(f"Total {c} divisors.")