# -*- coding: utf-8 -*-
"""Class Task _2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

n = int(input("Enter your number her : "))

c = 1
result = 0
while c <= n:

    if c % 2 == 0:
        result -= c**2
    else:
        result += c**2

    c += 1
print(result)