# -*- coding: utf-8 -*-
"""Home Task _8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

p = 0
r = 0
while p < 7:
   q = 1
   while q <= p:
       q = q + 1
       if q == 4 or q == 5:
           continue
           print(p - q * 2)
       elif p==6:
           break
           print(p % q)
       else:
           r = p * q - int(21 / q)
           print(r)
   p = p + 1

'''
-8
-6
-1
-4
2
-2
5
0
8
27
'''