# -*- coding: utf-8 -*-
"""Home Task _6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

x = 0
y = 0
q = 0
sum = 0
while (x < 10):
   p = 0.0
   p = x + y - sum + int(5 / 3) / 3.0 %  2 ** 3
   y = x // 5
   while (y  <  x):
       q = (x + 10.0) / 2
       sum =  (sum % 2) +  y  +  int(p)
       print(sum)
       y = y + 4
   if (x  >  5):
       x += 3
   else:
       x += 2
       print(int(p) + q)
print(sum - q)

'''
0
2
8.0
6
13.0
5
10
9
14
4.5
'''