# -*- coding: utf-8 -*-
"""Home Task _2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

num = input()
l = len(num)
print(l)
num = int(num)
i= 1

while num != 0:

    temp = num // (10**(l-i))

    if num < 10:
        print(temp,end = '')
    else:
        print(temp,end = ', ')

    num = num % (10**(l-i))

    i += 1

print(10**4)