# -*- coding: utf-8 -*-
"""Home Task _5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

h = int(input())


for i in range(1,h+1):

    for j in range(1,i+1):
        print(j,end='')
    print()