# -*- coding: utf-8 -*-
"""Class Task _2.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

st = input()

for i in st:
    print(f" {i}: {ord(i)}")