# -*- coding: utf-8 -*-
"""Class Task _3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

st = input()
char = input()

current = ''
splited = []

for i in st:

    if i != char:
        current += i

    else:
        splited.append(current)
        current = ''

splited.append(current)

for i in splited:
    print(i)