# -*- coding: utf-8 -*-
"""Class Task _2.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

st = input()

result = ''

for i in range(len(st)):

    if i % 2 != 0:
        result += st[i]

upper = ''

for i in result:

    if 'a' <= i <= 'z':

        upper += chr(ord(i) - 32)
    else:
        upper += i

print(upper)