# -*- coding: utf-8 -*-
"""Home Task _3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

st = input()

for i in st:
    if i == 'z':
        print(chr(97),end='')
    else:
        print(chr((ord(i)+1)),end='')