# -*- coding: utf-8 -*-
"""Home Task _4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

st = input()

c = 0
for i in st:

    if i == ' ':
        print(i,end = '')
    else:

        if  c % 2 == 0:
            if 'a' <= i <= 'z':
                print(chr(ord(i)-32),end = '')
                c +=1
            else:
                print(i,end = '')
                c += 1

        else:
            print(i,end = '')
            c += 1
