# -*- coding: utf-8 -*-
"""Class Task_1.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def is_pos(num):
    return num > 0

result = is_pos(-5)
print( result )
result = is_pos(12)
print( result )