# -*- coding: utf-8 -*-
"""Class Task_3.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def circle(r):

    return round((3.1416 * (r**2)),2)
circle(5)