# -*- coding: utf-8 -*-
"""Class Task_2.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def is_valid_triangle(x, y, z):
    if x + y > z and y + z > x and z + x > y:
        return True
    else:
        return False

def tri_area(m, n, o):
    if is_valid_triangle(m, n, o):
        s = (m + n + o) / 2
        area = round((s * (s - m) * (s - n) * (s - o)) ** 0.5,3)
        print(area)
    else:
        print("Can’t form triangle")

tri_area(3, 2, 1)
tri_area(7, 5, 10)