# -*- coding: utf-8 -*-
"""Class Task_5.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def recursive_summation(start,n):

    sum = 0
    for i in range(start,n+1):
        sum += i
    print(sum)

recursive_summation(1,12)