# -*- coding: utf-8 -*-
"""Class Task_3.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# def circle(r):

#     return round((3.1416 * (r**2)),2)

def sphere(r):
    return round((4/3)*3.1416*(r**3),2)
#circle(5)
sphere(5)