# -*- coding: utf-8 -*-
"""Home Task_5.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def sequence_iterative(n):

    sum = 0
    for i in range(1,n+1):

        if i % 2 == 0:
            sum -= i
        else:
            sum += i
    print(sum)

n = int(input())
sequence_iterative(n)