# -*- coding: utf-8 -*-
"""Home Task_5.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def sequence_iterative(n):

    if n == 1:
        return 1
    if n % 2 == 0:
        temp = -n
    else:
        temp = n
    return temp + sequence_iterative(n-1)

n = int(input())
print(sequence_iterative(n))