# -*- coding: utf-8 -*-
"""Home Task_4.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def power(a,n):

    if n == 0:
        return 1
    else:
        return a * power(a,n-1)

base = float(input("Enter the base (a): "))
exponent = int(input("Enter the exponent (n): "))

result = power(base, exponent)
print(f"{base}^{exponent} is equal to {result}")