# -*- coding: utf-8 -*-
"""Home Task_2.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

def show_dots(n):

    for i in range(n):
        print('.',end='')

show_dots(5)