# -*- coding: utf-8 -*-
"""dict_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

students_dict = {
    "Shaheen": {
        "roll": "12345",
        "gender": "Male",
        "Math": 95,
        "English": 85,
        "Science": 90,
        "History": 80,
    },
    "Shakil": {
        "roll": "67890",
        "gender": "Male",
        "Math": 78,
        "English": 88,
        "Science": 92,
        "History": 85,
    },
    "Arafat": {
        "roll": "54321",
        "gender": "Male",
        "Math": 85,
        "English": 92,
        "Science": 88,
        "History": 75,
    }
}
# print(students_dict)
# print(type(students_dict))

for k , v in students_dict.items():

    total_marks = v['Math'] + v['English'] + v['Science'] + v['History']
    print(f"{k}'s total marks is {total_marks} and gender is {v['gender']} ")