# -*- coding: utf-8 -*-
"""dict_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Ask subjects to the user and keep adding it to the dictionary and print it eventually

n = int(input("Enter the number of the subjects : "))

marks = {}

for _ in range(n):
    name = input("Enter the subjects name : ")
    m = input(f"Enter the marks for {name} :")
    marks[name] = m
   # marks.update({name:m })
print(marks)