# -*- coding: utf-8 -*-
"""dict_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Ask a string from the user and display the frequencey of each character solve aoo of this from this link (https://www.youtube.com/watch?v=l_AKp-1R4p8&list=PLhR2IpV1b2FzUivnn6TDCVb1ycWYYUmN8&index=58)

st = input("Enter your string here : ")

dct = {}

for i in range(len(st)):

    if st[i] in dct:
        dct[st[i]] += 1
    else:
        dct[st[i]] = 1
print(dct)