# -*- coding: utf-8 -*-
"""dict_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to sum all the items in a dictionary

dct = {
       'maths' : 88,
       'science' : 80,
       'bangla' : 80,
}
total = 1

for i in dct.values():
    total *= i
print(total)

print(sum(list(dct.values())))