# -*- coding: utf-8 -*-
"""dictionary

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

my_dict = {
    "name" : "Shaheen",
    "Age" : 26,
    "Gender" : "male"
}

for k in my_dict.items():
    print(f"{k[0]} -> {k[1]}")

for k,v in my_dict.items():
    print(f"{k} -> {v}")