# -*- coding: utf-8 -*-
"""dict_9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

students_dict = {
    "Arafat": {
        "roll": "54321",
        "gender": "Male",
        "marks": {
            "Math": 85,
            "English": 92,
            "Science": 88,
            "History": 75,
        }
    },
    "John": {
        "roll": "11111",
        "gender": "Male",
        "marks": {
            "Math": 90,
            "English": 85,
            "Science": 88,
            "History": 78,
        }
    },
    "Alice": {
        "roll": "22222",
        "gender": "Female",
        "marks": {
            "Math": 75,
            "English": 80,
            "Science": 92,
            "History": 88,

        }
    },
    "Bob": {
        "roll": "33333",
        "gender": "Male",
        "marks": {
            "Math": 88,
            "English": 90,
            "Science": 85,
            "History": 82,
        }
    }
}
for k , v in students_dict.items():

    total_marks = v['marks']['Math'] + v['marks']['English'] + v['marks']['Science'] + v['marks']['History']

    print(f"{k}'s total marks is {total_marks} and gender is {v['gender']} ")