# -*- coding: utf-8 -*-
"""dict_8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

students_dict = {
    "Shaheen": {
        "roll": "12345",
        "gender": "Female",
        "marks": [95, 85, 90, 80]
    },
    "Shakil": {
        "roll": "67890",
        "gender": "Male",
        "marks": [78, 88, 92, 85]
    },
    "Arafat": {
        "roll": "54321",
        "gender": "Male",
        "marks": [85, 92, 88, 75]
    }
}

for k , v in students_dict.items():

    #total_marks = sum(v['marks'])
    total_marks = 0
    for i in v['marks']:
        total_marks += i
    print(f"{k}'s total marks is {total_marks} and gender is {v['gender']} ")