# -*- coding: utf-8 -*-
"""dict_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Convert two list into dictionary

lst1 = ['Name', 'maths','English','Science']
lst2 = ['Shaheen',80,80,80]

result = {}

for i in range(len(lst1)):

    result[lst1[i]] = lst2[i]

print(result)