# -*- coding: utf-8 -*-
"""task_60

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

#  Write a program that can count the number of words in a given string without using the split()



x = "Shahidul Haque Shaheen"

#print(x)

c = 0

for i in x:
    if i == ' ':
        c += 1

c = c+1

print("The  number of words in the given string is : ",c)