# -*- coding: utf-8 -*-
"""task_31

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Print first 25 prime numbers
flag = 0
num = 2
prime_lst = []

while flag <= 25:

    for i in range(2,num):
        if num % i == 0:
            break
    else:
        print(num)
        flag += 1

    num += 1

