# -*- coding: utf-8 -*-
"""task_41

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

'''
Write a program to calculate the sum of the following series till the nth term
1/1! + 2/2! + 3/3! + 4/4! +…….+ n/n!
n will be provided by the user
'''

n = int(input("Enter your number here : "))

sum = 0

facto = 1

for i in range(1, n+1):

    facto = facto * i
    print(facto)

    sum = sum + (i / facto)

print("The sum of nth series is : ",sum)

# Using math library

'''
import math

def series(n):

    sum = 0

    for i in range(1, n+1):

        sum = sum + (i / math.factorial(i))

    return sum

print(series(5))
'''