# -*- coding: utf-8 -*-
"""task_81

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that prints a diamond

def diamond(h):

    for i in range(1,h+1):

        sp = ' ' * (h - i)
        st = "*" *(i*2 -1)
        print(sp+st)

    for j in range(h-1,0,-1):

        sp = ' ' * (h - j)
        st = "*" *(j*2 -1)
        print(sp+st)



diamond(5)