# -*- coding: utf-8 -*-
"""task_51

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that can check whether a given string is palindrome or not.

st = input("Enter your string here : ")

l = len(st)
flag = True

for i in range(l//2):

    if st[i] != st[l-i -1]:
        flag = False
if flag:
    print("Plaindrome")

else:
    print("Not a palindrome")