# -*- coding: utf-8 -*-
"""task_36

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

'''
Write a program to print the following pattern
*
**
***
****
*****
'''

for i in range(1,6):
    for j in range(i):

        print('*', end = "")

    print()

'''
Using single loop

for i in range(1, 6):
    print('*' * i)

'''

