# -*- coding: utf-8 -*-
"""task_24

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that can multiply 2 numbers provided by the user without using the * operator

x , y = map(int, input("Enter your numbers here : ").split())

res = 0

for i in range(y):
    res += x

print("Your result is : ", res)