# -*- coding: utf-8 -*-
"""task_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7WEiJQsG21IbHHiJ1mT25SMNmnyv23A
"""

#User will input (3ages).Find the oldest one

x, y, z = map(int, input("Enter three ages : ").split())

old = x

if old < y:
    old = y

if old < z:
    old = z

print("The oldest one among three is : ", old)