# -*- coding: utf-8 -*-
"""task_83

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

c = 1
for i in range(1,6):
    for j in range(1,i+1):
        print(c,end=" ")
        c += 1
    print()