# -*- coding: utf-8 -*-
"""task_27

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to print whether a given number is prime number or not

n = int(input("Enter your number to be checked whether is it prime or not : "))

if n == 2:
    print("It is a prime number")

elif n > 2:
    for i in range(2,n):

        if n % i == 0:
            print("It is not a prime number")
            break
    else:
        print("It is a prime number")
        
else:
    print("It is not a prime number")