# -*- coding: utf-8 -*-
"""task_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7WEiJQsG21IbHHiJ1mT25SMNmnyv23A
"""

# Write a program that will give you the sum of 3 digits

digits = int(input("Enter your three digits number : "))

x = digits % 10   # (259 % 2 = 9)

digits  = digits // 10  #(259 // 10 = 25)

y = digits % 10

z = digits // 10

sum  = x+y+z

print("The sum of three digits number : ", sum)