# -*- coding: utf-8 -*-
"""task_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7WEiJQsG21IbHHiJ1mT25SMNmnyv23A
"""

# User will input (2numbers).Write a program to swap the numbers

x, y = map(int, input("Enter two numbers : ").split())

temp = x
x = y
y = temp

print("Swapped value of X = ", x , "and Y = ", y)