# -*- coding: utf-8 -*-
"""task_56

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a python program to search a given number from a list

lst = [0, 9, 8, 6, 5, 34, 2, 1]

n  = int(input("Enter your number here : "))

for i in lst:

    if i == n:

        print("True")
        break
else:

    print("False")