# -*- coding: utf-8 -*-
"""task_22

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that will swap numbers without using temp variable

x , y = map(int, input("Enter your numbers here : ").split())

# temp = x
# x = y
# y = temp

x = x + y
y = x - y
x = x - y

print("The swaped vlaues are : ", x ," and ", y)