# -*- coding: utf-8 -*-
"""task_14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Angle between hour and minute hand

def getAngle(h,m):


    angle = (h*30 -((11/2)*m))

    if angle <= 180:

        return abs(angle)
    else:

        return abs(360 - angle)
H , M = map(int,input("Enter hour and minutes here : ").split())

print(getAngle(H,M))