# -*- coding: utf-8 -*-
"""task_17

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that will take three digits from the user and add the square of each digit

d = int(input("Enter your three digits number : "))

a = d % 10
a = a**2
d = d//10

b = d % 10
b = b**2
d = d//10

c = d
c = c**2

sum = a+b+c

print("Sum of the square of three digits given number : ", sum)