# -*- coding: utf-8 -*-
"""task_68

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to print the shape of a matrix.

matrix = [
    [1,2,3],
    [4,5,6],
    [5,6,9]
]

row = 0

for i in matrix:
    row += 1

print("The shape of the matrix is : ",row,"*",len(i))

