# -*- coding: utf-8 -*-
"""task_30

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to print all the unique combinations of 1,2,3 and 4

'''
lst = []
for i in range(1, 5):
    for j in range(1, 5):
        if i != j:
            lst.append((j,i))
            if (i,j) not in lst:
                print(i,j)
'''

for i in range(1, 5):
    for j in range(1, 5):

        if i != j:
            print(i,j)