# -*- coding: utf-8 -*-
"""task_40

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

'''
Write a program to print the following pattern
1
2 3
4 5 6
7 8 9 10


'''
r = int(input("Enter your row number : "))
x = 1
for i in range(r):

    for j in range(i):

        print(x, end = " ")
        x+=1
    print()