# -*- coding: utf-8 -*-
"""task_70

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to perform matrix multiplication on 2 matrices

matrix1 = [
    [1,2,3],
    [4,5,6],
    [5,6,9]
]


matrix2 = [
    [1,2],
    [4,5],
    [6,7]
]


result = []
for i in range(len(matrix1)):
    result.append([0] * len(matrix2[0]))

if len(matrix1[0]) != len(matrix2):
    print("Error: Matrix multiplication is not possible.")

for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            result[i][j] += matrix1[i][k] * matrix2[k][j]


print(result)

