# -*- coding: utf-8 -*-
"""task_69

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that can check if you can perform matrix multiplication on 2 matrices

matrix = [
    [1,2,3],
    [4,5,6],
    [5,6,9]
]

row_1 = 0

for i in matrix:
    row_1 += 1
    column_1 = len(i)

matrix = [
    [1,2],
    [4,5]
]

row_2 = 0

for i in matrix:
    row_2 += 1
    column_2 = len(i)

if column_1 == row_2:

    print("Possible")
else:
    print('Impossible')

