# -*- coding: utf-8 -*-
"""task_48

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Find the index position of a particular character in another string.

st = input("Enter your string here : ")

ch = input("Enter your character")


for i in st:

    if i == ch:

        print(st.index(i))