# -*- coding: utf-8 -*-
"""task_34

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Print all factors of a given number provided by the user.

n = int(input("Enter the number here : "))

for i in range(1,n+1):

    if n % i == 0:
        print(i, end = " ")

