# -*- coding: utf-8 -*-
"""task_26

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program to print the first 25 odd numbers

for i in range(1,50,2):
    print(i)

# Using while loop

'''

flag = 0

i = 1

while True:

    if i % 2 != 0:
        print(i)
        flag += 1
    if flag == 25:
        break
    i += 1

'''