# -*- coding: utf-8 -*-
"""task_57

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that can create a new list from a given list where each item in the new list is square of the item of the old list

lst = [0, 9, 8, 6, 5, 34, 2, 1]
n_lst = []



for i in lst:

    n_lst.append(i**2)

print(n_lst)