# -*- coding: utf-8 -*-
"""task_79

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a function that accepts a number and returns it’s factorial. You can not use any loop

def facto(num):

    if num == 1 or num == 0:
        return 1 # as factorial of o/1 is 1.

    else:
        return num * facto(num-1)


print(facto(5))

