# -*- coding: utf-8 -*-
"""task_71

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that can sort a given unsorted list. Dont use any built in function for sorting.

lst = [64, 25, 12, 22, 11]


# Selection Sort

for i in range(len(lst)):

    min_index = i

    for j in range(i+1,len(lst)):

        if lst[j] < lst[min_index]:

            min_index = j

    lst[i],lst[min_index] = lst[min_index],lst[i]


print("Sorted list : ", lst)

