# -*- coding: utf-8 -*-
"""task_82

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

my_dict = {
    'banana': 5,
    'apple': 10,
    'orange': 3,
    'grape': 8,
    'kiwi': 2
}

# Sorting by keys
sorted_by_keys = dict(sorted(my_dict.items()))
print("Sorted by keys:", sorted_by_keys)

# Sorting by values
sorted_by_values = dict(sorted(my_dict.items(), key=lambda item: item[1]))
print("Sorted by values:", sorted_by_values)

# Sorting by values in descending order
sorted_by_values_desc = dict(sorted(my_dict.items(), key=lambda item: item[1], reverse=True))
print("Sorted by values (descending):", sorted_by_values_desc)