# -*- coding: utf-8 -*-
"""task_65

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

# Write a program that can convert a 2D list to 1D list Write a program that can print

lst = [[2, 4],6, 8, 10, [100, 3, 5, 7, 9]]

l = []

for i in lst:
    if type(i) == list:
        for j in i:
            l.append(j)

    else:
        l.append(i)
print("Converted list : ",l)

