# -*- coding: utf-8 -*-
"""task_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GoKwkiQV9xBtVhhxX5Hh9j2-SlBHCJzS
"""
# Write a program that will reverse a four digit number.Also it checks whether the reverse is true.

digits = int(input("Enter a four-digit number: "))

temp = digits

d = temp % 10
temp = temp // 10

c = temp % 10
temp = temp // 10

y = temp % 10
temp = temp // 10

x = temp % 10

reversed_digit = 1000 * d + 100 * c + 10 * y + x

print("The reversed value of the four-digit number:", reversed_digit)

if digits == reversed_digit:
    print("True")
else:
    print("False")