# -*- coding: utf-8 -*-
"""Class Task _6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

p = 5
q = 6
r = 9
sum = 0
if (p < 12):
    print(r + 2)
else:
    print(r + p)
if (q > 20):
    print(r + 19)
elif (q <= 6):
    print(q + 3)
else:
    print(p + q + r)
if (r > 15):
    print(r)
elif (r == 0):
    print(p + q)
else:
    print(p)
if (sum != 0):
    print(3)
else:
    print(sum + 32)
if (p > 0 and r < 10):
    print(p + r)
else:
    print(p - r)

'''
Output:
11
9
5
32
14
'''