# -*- coding: utf-8 -*-
"""Class Task _5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

cgpa = float(input())
credits = int(input())

waiver = 0

if credits >= 30 and cgpa >= 3.8:
    if 3.8 <= cgpa <= 3.9:
        waiver = 25
    elif 3.90 <= cgpa <= 3.94:
        waiver = 50
    elif 3.95 <= cgpa <= 3.99:
        waiver = 75
    else:
        waiver = 100

    print(f"The student is eligible for a waiver of {waiver} percent")


else:
    print("The student is not eligible for a waiver")