# -*- coding: utf-8 -*-
"""Class Task _3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

num = int(input())

if num % 2 == 0 or num % 5 == 0:
    print(num)
else:
    print("Not a multiple of 2 OR 5")