# -*- coding: utf-8 -*-
"""L_136

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

class Solution(object):
    def singleNumber(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """

        dct = {}

        for i in nums:

            if i in dct:
                dct[i] += 1

            else:
                dct[i] = 1
        print(dct)
        for j in dct:

            if dct[j] == 1:
                return j