# -*- coding: utf-8 -*-
"""Task_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sRGxM9itgH14jeb4-cdcBGOE9mud9LuQ
"""

def partition(arr, l, r):
    pivot = arr[l] # 1st element as pivot
    i = l
    j = l+1

    while(j <= r):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
            j += 1
        else:
            j += 1

    arr[l], arr[i] = arr[i], arr[l]

    return i


def quick_sort(arr, start, end):
    if start >= end:
        return
    else:
        p = partition(arr, start, end)
        quick_sort(arr, start, p-1)
        quick_sort(arr, p+1, end)


input_5=open("/content/input5.txt","r")
output_5=open("/content/output5.txt","w")

n = int(input_5.readline().strip())
arr = input_5.readline().split()
arr = [int(i) for i in arr]

quick_sort(arr, 0, n-1)

for i in arr:
    output_5.write(f"{i} ")

input_5.close()
output_5.close()