# -*- coding: utf-8 -*-
"""Task_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sRGxM9itgH14jeb4-cdcBGOE9mud9LuQ
"""

def get_max(a):
     n = len(a)
     mid = n//2
     if n==1:
         return -9999999



     left_max = get_max(a[:mid])
     right_max = get_max(a[mid:])
     cross_max = max(a[:mid]) + max(abs(i) for i in a[mid:]) ** 2
     #print(cross_max)

     return max(left_max, right_max, cross_max)


input_4=open("/content/input4.txt","r")
output_4=open("/content/output4.txt","w")


n = int(input_4.readline().strip())
arr = input_4.readline().split()
arr = [int(i) for i in arr]

ans = get_max(arr)

output_4.write(f"{ans}")



input_4.close()
output_4.close()