# -*- coding: utf-8 -*-
"""task_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

import numpy as np

def selection(arr):

    for i in range(len(arr)):
        min_index = i

        for j  in range(i+1, len(arr)):
            if arr[j] < arr[min_index]:
                min_index = j

        arr[i],arr[min_index] = arr[min_index],arr[i]

    return arr

N = int(input("Enter your length of the array : "))
arr = np.empty(N,dtype = int)

for i in range(N):
    temp = int(input())
    arr[i] = temp

print(f"Original Array: {arr}")
print(f"Sorted Array: {selection(arr)}")