# -*- coding: utf-8 -*-
"""task_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

import numpy as np

def printPairs(arr, t):

    flag = False

    for i in range(len(arr)):
        for j in range(i+1,len(arr)):
            if arr[i] + arr[j] == t:
                print(f"{arr[i]}, {arr[j]}")
                flag = True
    if not flag:
        print("No Pair Found")


arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)
arr2 = np.array([2,-3,1,9,4,5])
printPairs(arr2, 6)
arr3 = np.array([5, 9, 7, 6, 10])
printPairs(arr3, 18)

# the above code takes O(n**2) time , lets solve this within O(n) time

'''
def printPairs(arr, t):

    dct = {}
    flag = False
    for i in range(len(arr)):
        target = t - arr[i]

        if target in dct:
            print(f"{target},{arr[i]}")
            flag = True

        dct[arr[i]] = i

    if not flag:
        print("No Pair Found")

arr3 = np.array([5, 9, 7, 6, 10])
printPairs(arr3, 18)
arr2 = np.array([2,-3,1,9,4,5])
printPairs(arr2, 6)
'''