# -*- coding: utf-8 -*-
"""task_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

import numpy as np

vec1 = np.array([1,2,3,7])
vec2 = np.array([4,5,6,9])
sum = 0

for i in range(len(vec1)):
    temp = vec1[i] * vec2[i]
    sum += temp

print(f"Dot Product: {sum}")

if sum % 2 == 0:
    for i in range(len(vec1)):
        if i % 2 == 0:
            vec1[i],vec2[i] = vec2[i],vec1[i]
else:
    for j in range(len(vec1)):
        if j % 2 != 0:
            vec1[j],vec2[j] = vec2[j],vec1[j]

print(vec1)
print(vec2)