# -*- coding: utf-8 -*-
"""task_8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

import numpy as np

def identify(a):

    flag = True
    for i in range(len(a)):

        for j in range(len(a[i])):

            if i == j and a[i,j] != 1:
                flag = False

            elif i != j and a[i,j] != 0:
                flag = False
    if flag:
        print("Identity Matrix")
    else:
        print("Not an Identity Matrix")


A = np.array([ [1, 0, 0],
[0, 1, 0],
[0, 0, 1] ])

identify(A)