# -*- coding: utf-8 -*-
"""task_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

import numpy as np

N = int(input("Enter the length of the the array : "))

arr = np.empty(N, dtype = int)

for i in range(N):
    arr[i] = int(input())
print(f"Original Array: {arr}")

new_value = int(input("Enter your last new value : "))

n_arr = np.empty(N+1, dtype = int)

for j in range(N):
    n_arr[j] = arr[j]
n_arr[N] = new_value

print(f"Resized Array: {n_arr}")
