# -*- coding: utf-8 -*-
"""task_9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

import numpy as np

def identify(a):

    sum1 = 0
    sum2 = 0
    for i in range(len(a)):
        for j in range(len(a[i])):
            if i == j:
                sum1 += a[i,j]
    c = 0
    for k in range(len(a)-1,-1,-1):
        for l in range(len(a[k])):
            if c == l:
                sum2 += a[k,l]
        c += 1
    print(abs(sum1 - sum2))

    # for k in range(len(a)-1,-1,-1):
    #     sum2 += a[k,len(a[k])-1-k]

    # print(sum1)
    # print(sum2)



A = np.array([  [1, 5, 12, 1],
                [2, -4, 6, 7],
                [3, 8, 5, 9],
                [3, 5, 23, -6] ])
identify(A)
'''
Using O(n) time
sum1 = sum(matrix[i, i] for i in range(rows))
sum2 = sum(matrix[i, rows - 1 - i] for i in range(rows))
'''

