# -*- coding: utf-8 -*-
"""task_11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

import numpy as np

def process_array(arr):

    rows, cols = arr.shape
    final_array = np.zeros_like(arr, dtype=float)

    absolute_difference = abs(rows - cols)
    remainder = absolute_difference % rows
    row_to_consider = remainder
    row_average = np.mean(arr[row_to_consider, :])

    for i in range(rows):
        for j in range(cols):
            final_array[i, j] = round(arr[i, j] * row_average, 2)

    return final_array

A = np.array([[6,3],
[1,5]])


result = process_array(A)

print("Original Array:")
print(A)
print("\nFinal Array:")
print(result)