# -*- coding: utf-8 -*-
"""Home Task _1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

print ("Hello")
x, y = 6, 10
print (x + y)
print (x**2)
print (y / 3)
print (y // 3)
print (y % y)
print (-5 / 2)
print (y > x)
print (y == x)
print (y >= x)
a = True
b = False
print (a and b)
print (a and not b)
y = x
print (y)
x = x + 2
print (x)
print ( x*y**2)
print (x == y*2//2 - 2**(2-1))
print (4+5.5)
print (x - y)
print (x * y)
print (y ** x)
print (x % y)
print (y % x)
print (y / y)
print (-5 // 2)
print (x > y)
print (y != x)
print (x <= y)
print (a)
print ("b")
print (a or b)
print (not a)
print (x)
x -= 2
x //= 1
print (x != y and a)
print (x+5*4%2-1)
print (x - ((x+y%2) *3)//2)