# -*- coding: utf-8 -*-
"""Home Task _2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

print ("Hello"+ "Hi")
print ("Hello"+ "  "+ "Hi")
print ("Hello", end= " ")
print ("Hi")
print ("Hello", "Hi")
print ("Hello")
print ("Hi")
print ("Hello", "Hi", end = "5")
print("Yo")
print ("Hi" + str(5))
print ("Hi" + str(5))
x=5
print (6 + int(x))
print ("Hi" * 3)