# -*- coding: utf-8 -*-
"""task_1.4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTJL4dlmNxiwlR333XY58zSGEUaxIMeK
"""

n1 = int(input("Enter your string here : "))
n2 = int(input("Enter your integer here : "))

n2 = float(n2)

n1 = str(n1)
n2 = str(n2)

sum = n1 + n2
print(sum)