# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sRGxM9itgH14jeb4-cdcBGOE9mud9LuQ
"""

def maximum_tasks(tasks):
    n = len(tasks)


    tasks.sort(key=lambda x: x[1])

    selected_tasks = []
    prev_end_time = -1

    for task in tasks:
        start_time, end_time = task
        if start_time >= prev_end_time:
            selected_tasks.append(task)
            prev_end_time = end_time

    return selected_tasks



input_3=open("/content/input3.txt","r")
output_3=open("/content/output3.txt","w")


n = int(input_3.readline().strip())

lst = []

for i in range(n):
    i = input_3.readline().split()
    i = (int(i[0]),int(i[1]))
    #print(i)
    lst.append(i)
#print(lst)
# min_couple = min(lst, key=lambda x: x[0])
#lst.sort(key=lambda x: x[1])
#print(lst)
#print(n)


result = maximum_tasks(lst)
output_3.write(f"{len(result)} \n")
for i in result:
    output_3.write(f"{i[0]} {i[1]} \n")
#print(result)


input_3.close()
output_3.close()